import { useEffect, useState, type ChangeEvent } from "react";
import { Download, FileBarChart, LoaderCircle, Printer, Upload, X } from "lucide-react";
import { commitImport, getReport, previewImport, type DuplicateDecision, type ImportPreview, type ReportData } from "./api";

const reportOptions = [
  ["tender-list", "Tender List"], ["pending-deadline", "Pending Deadline"], ["bank-charge", "Bank Charge"], ["pay-order", "Pay Order"], ["performance-security", "Performance Security"], ["win-lost", "Win / Lost"], ["tender-cost", "Tender Cost"]
] as const;
const display = (value: unknown, column = "") => {
  if (value == null || value === "") return "—";
  if (typeof value === "number" && /value|amount|cost|charge|security|pay order/i.test(column)) return `BDT ${new Intl.NumberFormat("en-BD", { maximumFractionDigits: 0, useGrouping: true }).format(value)}`;
  return String(value);
};

export function ImportModal({ onClose, onComplete }: { onClose: () => void; onComplete: (message: string) => void }) {
  const [preview, setPreview] = useState<ImportPreview | null>(null); const [decisions, setDecisions] = useState<Record<string, DuplicateDecision>>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const readFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setBusy(true); setError(""); try { const data = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",").at(-1) ?? ""); reader.onerror = () => reject(new Error("Unable to read file")); reader.readAsDataURL(file); }); setPreview(await previewImport({ filename: file.name, data })); } catch (e) { setError(e instanceof Error ? e.message : "Unable to parse import file"); } finally { setBusy(false); } };
  const commit = async () => { if (!preview) return; setBusy(true); setError(""); try { const result = await commitImport(preview, decisions); onComplete(`Imported ${result.imported.length}, updated ${result.updated.length}, skipped ${result.skipped.length}${result.errors.length ? `; ${result.errors.length} row errors` : ""}.`); onClose(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to commit import"); } finally { setBusy(false); } };
  return <div className="modal-backdrop" onMouseDown={(e) => e.target === e.currentTarget && !busy && onClose()}><section className="modal wide-modal" role="dialog" aria-modal="true"><div className="modal-head"><div><p className="eyebrow">Register intake</p><h2>Import Excel / CSV</h2></div><button type="button" className="icon-button" onClick={onClose}><X size={18} /></button></div><div className="import-body"><p className="import-help">Upload a .xlsx, .xls, or .csv file. Required columns: Tender ID, Company, Authority, Package Name, Closing At, Tender Value. Existing IDs are held for review before any changes are committed.</p><label className="file-drop"><Upload size={20} /><strong>{preview ? preview.filename : "Choose a local file"}</strong><span>Excel or CSV · first worksheet used</span><input type="file" accept=".xlsx,.xls,.csv,text/csv" onChange={readFile} /></label>{busy && <div className="inline-state"><LoaderCircle className="spin" size={18} /> Processing file…</div>}{preview && !busy && <><div className="import-summary"><span><strong>{preview.rows.length}</strong> rows</span><span><strong>{preview.validCount}</strong> valid</span><span className={preview.duplicates.length ? "warning-text" : ""}><strong>{preview.duplicates.length}</strong> duplicate reviews</span><span className={preview.invalidCount ? "error-text" : ""}><strong>{preview.invalidCount}</strong> invalid</span></div>{preview.duplicates.length > 0 && <div className="duplicate-review"><div className="section-heading"><div><p className="eyebrow">Decision queue</p><h3>Review duplicate Tender IDs</h3></div></div>{preview.duplicates.map((row) => <div className="duplicate-row" key={row.rowIndex}><div><strong>Row {row.rowIndex} · {display(row.tender.tenderId)}</strong><small>{row.duplicateOf ? `Existing: ${row.duplicateOf.company} · ${row.duplicateOf.packageName}` : `Duplicate of import row ${row.duplicateRow}`}</small></div><select value={decisions[String(row.rowIndex)] ?? "skip"} onChange={(e) => setDecisions((current) => ({ ...current, [row.rowIndex]: e.target.value as DuplicateDecision }))}><option value="keep-old">Keep old</option><option value="replace">Replace / update</option><option value="keep-both">Keep both</option><option value="skip">Skip row</option></select></div>)}</div>}{preview.invalidCount > 0 && <div className="form-error">Invalid rows will not be committed. Check required columns and date/amount formats.</div>}<div className="modal-actions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy || !preview.validCount} onClick={() => void commit()}>Commit import</button></div></>}</div>{error && <div className="form-error import-error">{error}</div>}</section></div>;
}

export function ReportsPage() {
  const [type, setType] = useState("tender-list"); const [report, setReport] = useState<ReportData | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const load = async (nextType = type) => { setLoading(true); setError(""); try { setReport(await getReport(nextType)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load report"); } finally { setLoading(false); } };
  useEffect(() => { void load("tender-list"); }, []);
  const select = (nextType: string) => { setType(nextType); void load(nextType); };
  return <section className="reports-layout"><div className="panel report-picker"><div className="panel-head"><div><p className="eyebrow">Management outputs</p><h2>Reports</h2></div><FileBarChart size={20} /></div><div className="report-options">{reportOptions.map(([value, label]) => <button key={value} className={type === value ? "selected" : ""} onClick={() => select(value)}>{label}</button>)}</div></div><section className="panel report-result"><div className="panel-head"><div><p className="eyebrow">{report?.title ?? "Select an output"}</p><h2>{report?.title ?? "Tender reports"}</h2></div><div className="report-actions"><a className="secondary" href={`/api/reports/${type}.csv`} download><Download size={15} /> CSV</a><a className="secondary" href={`/api/reports/${type}.pdf`} download><Download size={15} /> PDF</a><a className="secondary" href={`/api/reports/${type}/print`} target="_blank" rel="noreferrer"><Printer size={15} /> Print HTML</a></div></div>{loading ? <div className="table-state"><LoaderCircle className="spin" size={20} /> Loading report…</div> : error ? <div className="table-state error-state">{error}<button className="secondary" onClick={() => void load()}>Retry</button></div> : report ? <div className="table-wrap"><table><thead><tr>{report.columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{report.rows.length ? report.rows.map((row, index) => <tr key={index}>{report.columns.map((column) => <td key={column}>{display(row[column], column)}</td>)}</tr>) : <tr><td colSpan={report.columns.length} className="report-empty">No records match this report yet.</td></tr>}</tbody></table></div> : <div className="table-state">Choose a report to load.</div>}</section></section>;
}
