import { useEffect, useState } from "react";
import type { CompanySecuritySummary } from "../shared/domain";
import { ApiError, changeMasterPassword, clearCompanyCredentials, getCompanyCredentials, listCompanySecurity, lockMasterPassword, requestRecovery, saveCompanyCredentials, setupMasterPassword, unlockMasterPassword, updateRecoveryEmail, type CompanyCredentials, type SecurityStatus } from "./api";

interface SecurityPanelProps { status: SecurityStatus | null; onStatus: (status: SecurityStatus | null) => void; onNotice: (message: string) => void; }
const errorMessage = (error: unknown) => error instanceof Error ? error.message : "Security action failed.";

export function SecurityPanel({ status, onStatus, onNotice }: SecurityPanelProps) {
  const [setupPassword, setSetupPassword] = useState("");
  const [setupRecovery, setSetupRecovery] = useState("");
  const [unlockPassword, setUnlockPassword] = useState("");
  const [currentPassword, setCurrentPassword] = useState("");
  const [nextPassword, setNextPassword] = useState("");
  const [recoveryEmail, setRecoveryEmail] = useState("");
  const [recoveryRequestEmail, setRecoveryRequestEmail] = useState("");
  const [companies, setCompanies] = useState<CompanySecuritySummary[]>([]);
  const [selected, setSelected] = useState<CompanyCredentials | null>(null);
  const [credentialUsername, setCredentialUsername] = useState("");
  const [credentialPassword, setCredentialPassword] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState("");

  const refreshCompanies = async () => { try { setCompanies(await listCompanySecurity()); } catch (e) { setError(errorMessage(e)); } };
  useEffect(() => { if (status?.recoveryEmail !== undefined) setRecoveryEmail(status.recoveryEmail ?? ""); void refreshCompanies(); }, [status?.recoveryEmail]);

  const run = async (action: () => Promise<void>, message: string) => { setBusy(true); setError(""); try { await action(); onNotice(message); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } };
  const setup = (event: React.FormEvent) => { event.preventDefault(); void run(async () => { const session = await setupMasterPassword(setupPassword, setupRecovery); window.sessionStorage.setItem("tender-tracker-session", session.token); onStatus(session.status); setSetupPassword(""); }, "Master password configured. Protected credentials are now locked when you lock the app."); };
  const unlock = (event: React.FormEvent) => { event.preventDefault(); void run(async () => { const session = await unlockMasterPassword(unlockPassword); window.sessionStorage.setItem("tender-tracker-session", session.token); onStatus(session.status); setUnlockPassword(""); }, "App unlocked."); };
  const lock = () => void run(async () => { await lockMasterPassword(); window.sessionStorage.removeItem("tender-tracker-session"); onStatus(status ? { ...status, unlocked: false, sessionExpiresAt: undefined } : null); setSelected(null); }, "App locked. Credential values are hidden.");
  const reveal = (companyId: string) => void run(async () => { const credentials = await getCompanyCredentials(companyId); setSelected(credentials); setCredentialUsername(credentials.username); setCredentialPassword(credentials.password); }, "Credentials revealed for this session only.");
  const save = (companyId: string) => void run(async () => { await saveCompanyCredentials(companyId, credentialUsername, credentialPassword); await refreshCompanies(); setSelected(null); setCredentialUsername(""); setCredentialPassword(""); }, "Encrypted credentials saved.");
  const copy = async (label: string, value: string) => { try { await navigator.clipboard.writeText(value); setCopied(label); window.setTimeout(() => setCopied(""), 1600); } catch { setError("Clipboard access was blocked by the browser."); } };

  return <div className="security-stack">
    <section className="security-card"><div className="section-heading"><div><p className="eyebrow">One-owner protection</p><h3>{status?.configured ? "Master password" : "Set up master password"}</h3></div><span className={`security-state ${status?.unlocked ? "unlocked" : "locked"}`}>{status?.configured ? status.unlocked ? "Unlocked" : "Locked" : "Not configured"}</span></div>
      <p className="security-copy">The master password is hashed with Node scrypt and is never stored as plaintext. Credential values are encrypted with AES-256-GCM and only returned after an active local unlock session.</p>
      {!status?.configured ? <form className="security-form" onSubmit={setup}><label><span>Master password</span><input required minLength={12} type="password" autoComplete="new-password" value={setupPassword} onChange={(e) => setSetupPassword(e.target.value)} placeholder="At least 12 characters" /></label><label><span>Recovery email <small>Optional configuration</small></span><input type="email" value={setupRecovery} onChange={(e) => setSetupRecovery(e.target.value)} placeholder="owner@example.com" /></label><button className="primary" disabled={busy}>{busy ? "Setting up…" : "Set up protection"}</button></form> : !status.unlocked ? <form className="security-form" onSubmit={unlock}><label><span>Master password</span><input required autoComplete="current-password" type="password" value={unlockPassword} onChange={(e) => setUnlockPassword(e.target.value)} placeholder="Enter your master password" /></label><button className="primary" disabled={busy}>{busy ? "Unlocking…" : "Unlock app"}</button></form> : <div className="settings-actions"><button className="secondary" onClick={lock} disabled={busy}>Lock now</button><span className="security-copy-inline">Unlock session expires after 30 minutes of inactivity.</span></div>}
    </section>

    {status?.configured && <section className="security-card"><div className="section-heading"><div><p className="eyebrow">Owner settings</p><h3>Change master password</h3></div></div><form className="security-form" onSubmit={(event) => { event.preventDefault(); void run(async () => { const result = await changeMasterPassword(currentPassword, nextPassword); onStatus(result.status); setCurrentPassword(""); setNextPassword(""); }, "Master password changed and encrypted credentials re-keyed."); }}><label><span>Current password</span><input required type="password" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} /></label><label><span>New password</span><input required minLength={12} type="password" value={nextPassword} onChange={(e) => setNextPassword(e.target.value)} placeholder="At least 12 characters" /></label><button className="secondary" disabled={busy || !status.unlocked}>Change password</button></form></section>}

    {status?.configured && <section className="security-card"><div className="section-heading"><div><p className="eyebrow">Recovery metadata</p><h3>Recovery email</h3></div></div><p className="security-copy">Recovery is configuration-only in this local app. No email provider is connected and no email is sent. A recovery request records metadata for a future provider integration.</p>{status.unlocked ? <form className="security-form inline-security-form" onSubmit={(event) => { event.preventDefault(); void run(async () => { const result = await updateRecoveryEmail(recoveryEmail); onStatus(result.status); }, "Recovery email configuration saved."); }}><label><span>Owner recovery email</span><input type="email" value={recoveryEmail} onChange={(e) => setRecoveryEmail(e.target.value)} placeholder="owner@example.com" /></label><button className="secondary" disabled={busy}>Save email</button></form> : <form className="security-form inline-security-form" onSubmit={(event) => { event.preventDefault(); void run(async () => { const result = await requestRecovery(recoveryRequestEmail); if (!result.requested) throw new ApiError("No matching recovery email was found. No email was sent.", 400); }, "Recovery request metadata recorded; no email was sent."); }}><label><span>Configured recovery email</span><input required type="email" value={recoveryRequestEmail} onChange={(e) => setRecoveryRequestEmail(e.target.value)} placeholder="owner@example.com" /></label><button className="secondary" disabled={busy}>Record recovery request</button></form>}{status.recoveryResetRequestedAt && <p className="security-meta">Last request recorded {new Date(status.recoveryResetRequestedAt).toLocaleString()} · no provider delivery attempted.</p>}</section>}

    <section className="security-card"><div className="section-heading"><div><p className="eyebrow">e-Tender access</p><h3>Company credentials</h3></div><span className="panel-kicker">{companies.length} companies</span></div><p className="security-copy">Lists show only masked status. Username and password reveal actions require unlock; copy buttons write directly to the clipboard and do not appear in list responses.</p><div className="credential-list">{companies.map((company) => <div className="credential-row" key={company.id}><div><strong>{company.name}</strong><span>{company.hasCredentials ? (company.usernameMasked ?? "Credentials saved") : "No credentials saved"}</span></div><div className="credential-actions">{status?.unlocked && company.hasCredentials && <button className="secondary" onClick={() => reveal(company.id)}>Reveal</button>}{status?.unlocked && <button className="secondary" onClick={() => { setSelected({ companyId: company.id, companyName: company.name, username: "", password: "" }); setCredentialUsername(""); setCredentialPassword(""); }}>Edit</button>}</div></div>)}{!companies.length && <div className="inline-state">Create a tender company first, then manage its e-Tender credentials here.</div>}</div>{selected && status?.unlocked && <div className="credential-editor"><div className="section-heading"><div><p className="eyebrow">{selected.companyName}</p><h3>Protected credential editor</h3></div><button type="button" className="icon-button" aria-label="Close credential editor" onClick={() => setSelected(null)}>×</button></div><label><span>e-Tender username</span><input value={credentialUsername} onChange={(e) => setCredentialUsername(e.target.value)} autoComplete="off" /></label><label><span>e-Tender password</span><input type="password" value={credentialPassword} onChange={(e) => setCredentialPassword(e.target.value)} autoComplete="new-password" /></label><div className="settings-actions"><button className="primary" onClick={() => save(selected.companyId)} disabled={busy}>Save encrypted credentials</button>{credentialUsername && <button className="secondary" onClick={() => void copy("username", credentialUsername)}>{copied === "username" ? "Copied" : "Copy username"}</button>}{credentialPassword && <button className="secondary" onClick={() => void copy("password", credentialPassword)}>{copied === "password" ? "Copied" : "Copy password"}</button>}<button className="secondary" onClick={() => void run(async () => { await clearCompanyCredentials(selected.companyId); await refreshCompanies(); setSelected(null); }, "Credentials cleared.")}>Clear</button></div></div>}</section>
    {error && <div className="form-error">{error}</div>}
  </div>;
}
